# -*- coding: utf-8 -*-
"""binary_addition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qngbDBw5KwxWmvl_YzjN83q9XiilNBD
"""

# the user inputs the number of binary bits and two base-10 numbers to add. the code outputs the result in binary and displays whether it is an overflow or not.

while True:
  try:
    a = int(input("How many bits are we working with today? "))
    if a > 0:
      break
    else:
      print("Invalid input. Please enter a positive number.")
  except ValueError:
    print("Invalid input. Please enter a number.")

while True:
  try:
    b = int(input("Please enter the first base-10 number to add: "))
    c = int(input("Please enter the second base-10 number to add: "))
    break
  except ValueError:
    print("Invalid input. Please enter a number.")

if b + c >= 2**a - 1:
  print("Overflow! ")
else:
  pass

def modular_addition(b, c):
  modulo = int(2**a)
  sum = int((b + c) % modulo)
  def binary(sum):
    remainders = ""
    while sum > 0:
      remainder = sum % 2
      remainders = str(remainder) + remainders
      sum = sum // 2
    return remainders
  remainders = binary(sum)

  print("The base-10 result is: ", b + c)
  print("The modulo result is: ", sum, "mod", modulo)
  print("The binary result is: ", remainders)

modular_addition(b, c)

# lessons learned
# try-except loops make the prompt repeat itself until a satisfactory input type is achieved
# while True - as long as the program is running
# there are two ways to convert base 10 to binary
# 1. largest to smallest bit: check individual powers of 2; if the largest fits, write a 1 in that digit, subtract that value, repeat.
# 2. smallest to largest bit: note remainder mod 2, divide number by 2, repeat & put new remainders to the left of existing string
# second method is better for code as you don't need to know the largest power of 2 represented